version: '3.8'
services:
  tms-db:
    image: postgres:16-alpine
    container_name: tms-db
    environment:
      - POSTGRES_DB=tms_db
      - POSTGRES_USER=tms_user
      - POSTGRES_PASSWORD=ali08621568
    volumes:
      - tms_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tms-network

  tms-backend:
    build: .
    container_name: tms-backend
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - DB_HOST=tms-db
      - DB_PORT=5432
      - DB_NAME=tms_db
      - DB_USER=tms_user
      - DB_PASSWORD=ali08621568
      - CORS_ORIGINS=https://tms.mkmr.pro
    depends_on:
      - tms-db
    restart: unless-stopped
    networks:
      - tms-network

networks:
  tms-network:
    driver: bridge

volumes:
  tms_db_data: