spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: updateg
  flyway:
    enabled: true
tms:
  jwt:
    secret: ${JWT_SECRET}
  cors:
    allowed-origins: ${CORS_ORIGINS}
springdoc:
  swagger-ui:
    enabled: false