version: '3.8'
services:
  tms-db:
    image: postgres:16-alpine
    container_name: tms-db
    environment:
      - POSTGRES_DB=tms
      - POSTGRES_USER=tms_user
      - POSTGRES_PASSWORD=CHANGEZ_MOI
    volumes:
      - tms_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tms-network

  tms-backend:
    build: .
    container_name: tms-backend
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tms-db:5432/tms
      - SPRING_DATASOURCE_USERNAME=tms_user
      - SPRING_DATASOURCE_PASSWORD=ali08621568
    depends_on:
      - tms-db
    restart: unless-stopped
    networks:
      - tms-network

networks:
  tms-network:
    driver: bridge

volumes:
  tms_db_data: