package com.transport.tms.utils;

public interface Constants {

  String APP_ROOT = "/api/v1";

  String COMMANDE_FOURNISSEUR_ENDPOINT = APP_ROOT + "/commandesfournisseurs";
  String CREATE_COMMANDE_FOURNISSEUR_ENDPOINT = COMMANDE_FOURNISSEUR_ENDPOINT + "/create";
  String FIND_COMMANDE_FOURNISSEUR_BY_ID_ENDPOINT = COMMANDE_FOURNISSEUR_ENDPOINT + "/{idCommandeFournisseur}";
  String FIND_COMMANDE_FOURNISSEUR_BY_CODE_ENDPOINT = COMMANDE_FOURNISSEUR_ENDPOINT + "/filter/{codeCommandeFournisseur}";
  String FIND_ALL_COMMANDE_FOURNISSEUR_ENDPOINT = COMMANDE_FOURNISSEUR_ENDPOINT + "/all";
  String DELETE_COMMANDE_FOURNISSEUR_ENDPOINT = COMMANDE_FOURNISSEUR_ENDPOINT + "/delete/{idCommandeFournisseur}";

  String ENTREPRISE_ENDPOINT = APP_ROOT + "/entreprises";

  String FOURNISSEUR_ENDPOINT = APP_ROOT + "/fournisseurs";

  String UTILISATEUR_ENDPOINT = APP_ROOT + "/utilisateurs";

  String VENTES_ENDPOINT = APP_ROOT + "/ventes";

  String AUTHENTICATION_ENDPOINT = APP_ROOT + "/auth";

  // Bon de Réception
  String BON_RECEPTION_ENDPOINT = APP_ROOT + "/bonsreception";
  String CREATE_BON_RECEPTION_ENDPOINT = BON_RECEPTION_ENDPOINT + "/create";
  String FIND_BON_RECEPTION_BY_ID_ENDPOINT = BON_RECEPTION_ENDPOINT + "/{idBonReception}";
  String FIND_ALL_BON_RECEPTION_ENDPOINT = BON_RECEPTION_ENDPOINT + "/all";
  String DELETE_BON_RECEPTION_ENDPOINT = BON_RECEPTION_ENDPOINT + "/delete/{idBonReception}";

  // Bon de Retour Fournisseur
  String BON_RETOUR_FOURNISSEUR_ENDPOINT = APP_ROOT + "/bonsretour";
  String CREATE_BON_RETOUR_FOURNISSEUR_ENDPOINT = BON_RETOUR_FOURNISSEUR_ENDPOINT + "/create";
  String FIND_BON_RETOUR_FOURNISSEUR_BY_ID_ENDPOINT = BON_RETOUR_FOURNISSEUR_ENDPOINT + "/{idBonRetour}";
  String FIND_ALL_BON_RETOUR_FOURNISSEUR_ENDPOINT = BON_RETOUR_FOURNISSEUR_ENDPOINT + "/all";
  String DELETE_BON_RETOUR_FOURNISSEUR_ENDPOINT = BON_RETOUR_FOURNISSEUR_ENDPOINT + "/delete/{idBonRetour}";

  // Facture Fournisseur
  String FACTURE_FOURNISSEUR_ENDPOINT = APP_ROOT + "/facturesfournisseur";
  String CREATE_FACTURE_FOURNISSEUR_ENDPOINT = FACTURE_FOURNISSEUR_ENDPOINT + "/create";
  String FIND_FACTURE_FOURNISSEUR_BY_ID_ENDPOINT = FACTURE_FOURNISSEUR_ENDPOINT + "/{idFactureFournisseur}";
  String FIND_ALL_FACTURE_FOURNISSEUR_ENDPOINT = FACTURE_FOURNISSEUR_ENDPOINT + "/all";
  String DELETE_FACTURE_FOURNISSEUR_ENDPOINT = FACTURE_FOURNISSEUR_ENDPOINT + "/delete/{idFactureFournisseur}";

  // Avoir Fournisseur
  String AVOIR_FOURNISSEUR_ENDPOINT = APP_ROOT + "/avoirsfournisseur";
  String CREATE_AVOIR_FOURNISSEUR_ENDPOINT = AVOIR_FOURNISSEUR_ENDPOINT + "/create";
  String FIND_AVOIR_FOURNISSEUR_BY_ID_ENDPOINT = AVOIR_FOURNISSEUR_ENDPOINT + "/{idAvoirFournisseur}";
  String FIND_ALL_AVOIR_FOURNISSEUR_ENDPOINT = AVOIR_FOURNISSEUR_ENDPOINT + "/all";
  String DELETE_AVOIR_FOURNISSEUR_ENDPOINT = AVOIR_FOURNISSEUR_ENDPOINT + "/delete/{idAvoirFournisseur}";
}
